
[package]
name = "linux-proc-modifier"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"         
crossterm = "0.27"  
rayon = "1.10"      
clap = { version = "4.4", features = ["derive"] }  
bytemuck = "1.14"   
